### PR TITLE
better error handling for download_links.py

### PR DESCRIPTION
**Pull request by jaredb1011**
- Adds in error handling for a few common errors.
- Adds a minimum resolution option
- Retries unsuccessful downloads

### CODE REVIEW

**Comment by jaredb1011** [comment]
I am giving up on the github actions for now because it is being rather annoying. Would appreciate any advice from anyone who is more familiar than I am with Actions

**Comment by Why-Ay-Es-Haitch** [comment]
Don't think you should worry about using conda for the environment building. It won't be worth it until the amount of time taken to build is comparable between conda and pip. Otherwise we will just be using up our github billable hours. If there are any discrepancies between environments at this stage that cause pylint to go haywire just pylint ignore it.

**Review by Joe-TheBro — APPROVED** [review]
lgtm, we might want to add an issue on github to let people know we are still working on linting, put it under like enhancements and blocked or something.

**Comment by jaredb1011** [comment]
> 

I've created a new github issue to fix the pylint issue.

**Comment by Why-Ay-Es-Haitch** [comment]
This works fine for now. There's a couple of changes that might make for easier productionalization down the line, but I'll just pull all those into an enhancement for better workload chunking. That should allow some new people to get a good first issue so they can contribute and also free up some core dev time for more pressing matters.

**Review by Why-Ay-Es-Haitch — APPROVED** [review]

**Pull request merged**
